version: "3.9"
name: starlette_snippet

services:
  web:
    image: "starlette_snippet:latest"
    env_file:
      - ../src/config/settings/.local
    build:
      context: ../
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ../:/code
